source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

gem 'haml-rails'

gem 'bootstrap-sass', github: 'thomas-mcdonald/bootstrap-sass'
gem 'b3form', path: '../..'

group :development do
  gem 'pry-rails'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end
